on:
  workflow_dispatch: {}

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ./
          key:  cache-2314628
      - name: prime-cache-2314628
        run: |
          echo ${{ steps.cache.outputs.cache-hit }}
        shell: bash
